services:
  db:
    image: postgres:14
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456admin
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Asegúrate de mapear el puerto 5432
    networks:
      - app_network

  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=store_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456admin
      - DB_HOST=db  # Usar 'db' como el nombre del servicio de PostgreSQL
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
    driver: bridge
