services:
  db:
    image: postgres:14
    restart: always
    container_name: postgresql
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456admin
    ports:
      - "5432:5432"  # Puerto mapeado de PostgreSQL (host:container)

  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000  # Cambiado a 8000
    volumes:
      - .:/app  # Cambiado a /app, que es el directorio de trabajo en el Dockerfile
    ports:
      - "8000:8000"  # Mapea el mismo puerto dentro y fuera del contenedor
    environment:
      - POSTGRES_NAME=store_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456admin
      - POSTGRES_HOST=db  # Asegura que el host sea el nombre del servicio de la base de datos
      - POSTGRES_PORT=5432  # Puerto interno del contenedor de PostgreSQL
    depends_on:
      - db

volumes:
  db-data:
