name: Django CI with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U user" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Construir y correr contenedor
      - name: Build and run Docker container
        run: |
          docker-compose -f docker-compose.yml up --build -d
          docker-compose exec web python manage.py migrate

      # Paso 4: Pruebas
      - name: Run Django tests
        run: |
          docker-compose exec web python manage.py test

      # Paso 5: Detener los contenedores
      - name: Shut down containers
        run: docker-compose down
